---
stages:
  - test

.test: &test
  stage: test
  image: nesachirou/elixir:${IMAGE}
  script:
    - mix deps.get
    - mix cotton.lint
    - mix coveralls
  cache:
    key: $IMAGE
    paths:
      - _build
      - deps

test-1.12_erl24:
  <<: *test
  variables:
    IMAGE: 1.12_erl24
# test-1.12_erl25:
#   <<: *test
#   variables:
#     IMAGE: 1.12_erl25
test-1.13_erl24:
  <<: *test
  variables:
    IMAGE: 1.13_erl24
test-1.13_erl25:
  <<: *test
  variables:
    IMAGE: 1.13_erl25
