---
language: elixir
cache:
  directories:
    - "_build"
    - "deps"
elixir:
  - "1.9"
  - "1.10"
otp_release:
  - "22.3"
  - "23.0"
jobs:
  exclude:
    - elixir: "1.9"
      otp_release: "23.0"
script:
  - "mix cotton.lint"
  - "mix coveralls.travis"
