language: elixir
cache: 
  directories: 
    - "_build"
    - "deps"
elixir: 
  - "1.7"
  - "1.8"
matrix: 
  exclude: []
otp_release: 
  - "21.3"
  - "22.0"
script: 
  - "mix cotton.lint"
  - "mix coveralls.travis"