---
stages:
  - test

.test: &test
  stage: test
  image: nesachirou/elixir:${IMAGE}
  script:
    - mix deps.get
    - mix cotton.lint
    - mix coveralls
  cache:
    key: $IMAGE
    paths:
      - _build
      - deps

test-1.13_erl25:
  <<: *test
  variables:
    IMAGE: 1.13_erl25
#test-1.13_erl26:
#  <<: *test
#  variables:
#    IMAGE: 1.13_erl26
test-1.14_erl25:
  <<: *test
  variables:
    IMAGE: 1.14_erl25
test-1.14_erl26:
  <<: *test
  variables:
    IMAGE: 1.14_erl26
