---
stages:
  - test

.test: &test
  stage: test
  image: nesachirou/elixir:${IMAGE}
  script:
    - mix "do" deps.get, cotton.lint
    - mix coveralls
  cache:
    key: $IMAGE
    paths:
      - _build
      - deps

test-1.10_erl22:
  <<: *test
  variables:
    IMAGE: 1.10_erl22
test-1.10_erl23:
  <<: *test
  variables:
    IMAGE: 1.10_erl23
test-1.11_erl22:
  <<: *test
  variables:
    IMAGE: 1.11_erl22
test-1.11_erl23:
  <<: *test
  variables:
    IMAGE: 1.11_erl23
