---
language: elixir
cache:
  directories:
    - "_build"
    - "deps"
elixir:
  - "1.12"
  - "1.13"
otp_release:
  - "24.0"
  - "25.0"
jobs:
  exclude:
    - elixir: "1.12"
      otp_release: "25.0"
script:
  - "mix cotton.lint"
  - "mix coveralls.travis"
