---
language: elixir
cache:
  directories:
    - "_build"
    - "deps"
elixir:
  - "1.13"
  - "1.14"
otp_release:
  - "25.0"
  - "26.0"
jobs:
  exclude:
    - elixir: "1.13"
      otp_release: "26.0"
script:
  - "mix cotton.lint"
  - "mix coveralls.travis"
