---
language: elixir
cache:
  directories:
    - "_build"
    - "deps"
elixir:
  - "1.12"
  - "1.13"
otp_release:
  - "23.0"
  - "24.0"
jobs:
  exclude: []
script:
  - "mix cotton.lint"
  - "mix coveralls.travis"
