---
name: test

"on":
  pull_request:
  push:
    branches:
      - main
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        elixir: ["1.13.x", "1.14.x"]
        erlang: ["24.x", "25.x"]
        os: [ubuntu-latest]
        exclude: []
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.erlang }}
      - uses: actions/cache@v3
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-erl${{ matrix.erlang }}-ex${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-erl${{ matrix.erlang }}-ex${{ matrix.elixir }}-
            ${{ runner.os }}-erl${{ matrix.erlang }}-
      - name: Install Elixir dependencies
        run: mix "do" deps.get, deps.clean --unused
      - name: Lint & test
        run: |
          mix cotton.lint
          mix coveralls.github
