---
'on':
  pull_request:
  push:
    branches:
      - main
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        elixir: ['1.10.x', '1.11.x']
        erlang: ['22.x', '23.x']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.erlang }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-erl${{ matrix.erlang }}-ex${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-erl${{ matrix.erlang }}-ex${{ matrix.elixir }}-
            ${{ runner.os }}-erl${{ matrix.erlang }}-
      - name: Lint & test
        run: |
          mix "do" local.hex --force, local.rebar --force
          mix "do" deps.get, deps.clean --unused, cotton.lint
          mix coveralls.github
